# Generated by Django 6.0.2 on 2026-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company_slug',
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
