# Generated by Django 6.0.2 on 2026-07-06 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_remove_booking_date_time_and_more'),
        ('companies', '0004_remove_company_unique_company_slug_and_more'),
        ('customers', '0004_customer_is_active'),
        ('employees', '0005_employee_is_active'),
        ('services', '0004_rename_desciption_service_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='bookings_bo_start_t_3f3843_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['employee'], name='bookings_bo_employe_75ac1e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company'], name='bookings_bo_company_015739_idx'),
        ),
    ]
