# Generated by Django 6.0.2 on 2026-07-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options_remove_booking_date_and_more'),
        ('companies', '0004_remove_company_unique_company_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.company'),
        ),
    ]
