# Generated by Django 6.0.5 on 2026-06-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='services_se_name_32d28c_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'slug'), name='unique_service_slug')],
            },
        ),
    ]
