# Generated by Django 5.1.7 on 2026-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
