# Generated by Django 5.1.7 on 2026-07-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_desciption_alter_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desciption',
            new_name='description',
        ),
    ]
