# Generated by Django 6.0.2 on 2026-07-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_desciption_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='time',
            new_name='duration',
        ),
    ]
